In [1]:
import pandas as pd
dataset = pd.read_csv("iphone_purchase_records.csv")

In [2]:
dataset.head()

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [3]:
dataset.describe()

Age         Salary  Purchase Iphone
count  400.000000     400.000000       400.000000
mean    37.655000   69742.500000         0.357500
std     10.482877   34096.960282         0.479864
min     18.000000   15000.000000         0.000000
25%     29.750000   43000.000000         0.000000
50%     37.000000   70000.000000         0.000000
75%     46.000000   88000.000000         1.000000
max     60.000000  150000.000000         1.000000

In [4]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

In [5]:
from sklearn.preprocessing import LabelEncoder
labelEncoder_gender = LabelEncoder()
X[:,0] = labelEncoder_gender.fit_transform(X[:,0])

In [6]:
# if you wan to convert x to float data 
# it is optional
import numpy as np 
X = np.vstack(X[:,:]).astype(np.float)

In [7]:
print(X)

[[1.0e+00 1.9e+01 1.9e+04]
 [1.0e+00 3.5e+01 2.0e+04]
 [0.0e+00 2.6e+01 4.3e+04]
 ...
 [0.0e+00 5.0e+01 2.0e+04]
 [1.0e+00 3.6e+01 3.3e+04]
 [0.0e+00 4.9e+01 3.6e+04]]


In [8]:
# step 3 - split the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=0)

In [9]:
# step 4 - Fit classifier
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [10]:
# Step 5 - Predict
y_pred = classifier.predict(X_test)

In [11]:
# step 6 - metrics
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred)
cm

array([[64,  4],
       [ 4, 28]], dtype=int64)

In [12]:
accuracy = metrics.accuracy_score(y_test, y_pred)  ## 0.92
accuracy

0.92

In [13]:
precision = metrics.precision_score(y_test, y_pred)  ## 0.85
recall = metrics.recall_score(y_test, y_pred)  ## 0.90
precision,recall

(0.875, 0.875)

In [14]:
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1]
